global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'jenkins-rollback-webhook'

receivers:
  - name: 'jenkins-rollback-webhook'
    webhook_configs:
      - url: 'http://13.63.41.103:8080/generic-webhook-trigger/invoke?token=ROLLBACK_5C6721_TOKEN'
        http_config:
          basic_auth:
            username: 'admin'
            password: '11e98ca7960c72f9e1ecaa3ade287afa18'
        send_resolved: false
