global:
  resolve_timeout: 5m

route:
  receiver: 'jenkins-rollback-webhook'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'jenkins-rollback-webhook'
    webhook_configs:
      - url: 'http://16.192.5.17:8080/generic-webhook-trigger/invoke?token=ROLLBACK_5C6721_TOKEN'
        send_resolved: false
